# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ip_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ip(object):
    def setupUi(self, Ip):
        Ip.setObjectName("Ip")
        Ip.resize(365, 290)
        self.centralwidget = QtWidgets.QWidget(Ip)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 90, 211, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        Ip.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ip)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 365, 21))
        self.menubar.setObjectName("menubar")
        Ip.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ip)
        self.statusbar.setObjectName("statusbar")
        Ip.setStatusBar(self.statusbar)

        self.retranslateUi(Ip)
        QtCore.QMetaObject.connectSlotsByName(Ip)

    def retranslateUi(self, Ip):
        _translate = QtCore.QCoreApplication.translate
        Ip.setWindowTitle(_translate("Ip", "MainWindow"))
        self.label.setText(_translate("Ip", "Введите IP.v4 сервера"))
