# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(200, 200)
        LoginWindow.setMinimumSize(QtCore.QSize(200, 200))
        LoginWindow.setMaximumSize(QtCore.QSize(200, 200))
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 182, 146))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ErrorLable = QtWidgets.QLabel(self.widget)
        self.ErrorLable.setMinimumSize(QtCore.QSize(180, 24))
        self.ErrorLable.setMaximumSize(QtCore.QSize(180, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ErrorLable.setFont(font)
        self.ErrorLable.setText("")
        self.ErrorLable.setAlignment(QtCore.Qt.AlignCenter)
        self.ErrorLable.setObjectName("ErrorLable")
        self.verticalLayout.addWidget(self.ErrorLable)
        self.Name = QtWidgets.QLineEdit(self.widget)
        self.Name.setMinimumSize(QtCore.QSize(180, 24))
        self.Name.setMaximumSize(QtCore.QSize(180, 24))
        self.Name.setObjectName("Name")
        self.verticalLayout.addWidget(self.Name)
        self.Password = QtWidgets.QLineEdit(self.widget)
        self.Password.setMinimumSize(QtCore.QSize(180, 24))
        self.Password.setMaximumSize(QtCore.QSize(180, 24))
        self.Password.setObjectName("Password")
        self.verticalLayout.addWidget(self.Password)
        self.Login = QtWidgets.QPushButton(self.widget)
        self.Login.setMinimumSize(QtCore.QSize(180, 24))
        self.Login.setMaximumSize(QtCore.QSize(180, 24))
        self.Login.setObjectName("Login")
        self.verticalLayout.addWidget(self.Login)
        self.Register = QtWidgets.QPushButton(self.widget)
        self.Register.setMinimumSize(QtCore.QSize(180, 24))
        self.Register.setMaximumSize(QtCore.QSize(180, 24))
        self.Register.setObjectName("Register")
        self.verticalLayout.addWidget(self.Register)
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 200, 21))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.Name.setPlaceholderText(_translate("LoginWindow", "Name"))
        self.Password.setPlaceholderText(_translate("LoginWindow", "Password"))
        self.Login.setText(_translate("LoginWindow", "Login"))
        self.Register.setText(_translate("LoginWindow", "Register"))
