# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'waiting_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Waiting(object):
    def setupUi(self, Waiting):
        Waiting.setObjectName("Waiting")
        Waiting.resize(575, 314)
        self.centralwidget = QtWidgets.QWidget(Waiting)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 70)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.Players = QtWidgets.QLabel(self.centralwidget)
        self.Players.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Players.setAlignment(QtCore.Qt.AlignCenter)
        self.Players.setObjectName("Players")
        self.verticalLayout.addWidget(self.Players)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMinimum(1)
        self.progressBar.setMaximum(2)
        self.progressBar.setProperty("value", 2)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        Waiting.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Waiting)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 575, 21))
        self.menubar.setObjectName("menubar")
        Waiting.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Waiting)
        self.statusbar.setObjectName("statusbar")
        Waiting.setStatusBar(self.statusbar)

        self.retranslateUi(Waiting)
        QtCore.QMetaObject.connectSlotsByName(Waiting)

    def retranslateUi(self, Waiting):
        _translate = QtCore.QCoreApplication.translate
        Waiting.setWindowTitle(_translate("Waiting", "MainWindow"))
        self.label.setText(_translate("Waiting", "Waite for other players"))
        self.Players.setText(_translate("Waiting", "TextLabel"))
